[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-http-proxy"
version = "0.1.0"

[dependencies]
twilight-http = { git = "https://github.com/rxdn/twilight/", branch = "api-v9", default-features = false, features = ["rustls"] }
hyper = { version = "0.14", features = ["tcp", "server", "http1", "http2"] }
http = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "registry"] }
tracing-log = "0.1"
snafu = "0.6"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }

# Only used by the `expose-metrics` feature.
prometheus = { version = "0.11", optional = true }
lazy_static = { version = "1.4", optional = true }

[features]
default = []
expose-metrics = ["prometheus", "lazy_static"]
